### ISSUE TITLE
Message: Request markdown/parse failed with message: Expected a code point, got undefined. Code: -32603

### ISSUE THREAD

**Issue by rsholmqvist** [searKing/preview-vscode#87] opened 2024-05-13 23:39 UTC
please see details in https://github.com/microsoft/vscode/issues/210913

I used Extension bisect to determine this extension is causing the issue

Request textDocument/codeAction failed.
Message: Request markdown/parse failed with message: Expected a code point, got undefined.
Code: -32603

Details of failure are in
https://github.com/microsoft/vscode/issues/210913#issuecomment-2093046197
https://github.com/microsoft/vscode/issues/210913#issuecomment-2108770129

This is my help:about
```
Version: 1.89.0 (user setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```

More Info
```
Published
2016-05-10, 04:27:07
Last released
2024-04-25, 02:47:25
Last updated
2024-04-25, 08:28:57
Identifier
searking.preview-vscode
```

**Comment by searKing** [comment] 2024-05-14 05:36
+ Thanks! This is caused by the official markdown-it plugin [markdown-it-cjk-breaks](https://github.com/markdown-it/markdown-it-cjk-breaks/blob/master/index.mjs#L49).
+ I have created a MR to fix, details in https://github.com/markdown-it/markdown-it-cjk-breaks/pull/5.
+ Update to Preview@2.3.7 please, `markdown-it-cjk-breaks` is replaced with `@searking/markdown-it-cjk-breaks` until the MR is merged.

**Closed by searKing** 2024-05-14 05:36 UTC
Labels: bug
