### ISSUE TITLE
No Active editor - no properties to preview

### ISSUE THREAD

**Issue by MrMYHuang** [searKing/preview-vscode#14] opened 2017-04-20 21:26 UTC
# Issue
I press "Ctrl+K, V" for previewing a .rst file. But I got a window with only this message:
No Active editor - no properties to preview.

# Software Versions
vscode: 1.11.2
preview-vscoe: 1.1.5
OS: Windows 10 64-bit ver. 1703 and CentOS 7

**Comment by leingang** [comment] 2017-05-30 13:42
I have the exact same issue, in vscode 1.12.2 and preview 1.1.5

**Comment by windperson** [comment] 2017-06-09 08:57
Use **Open|Close Preview to the Side** ( ctrl+k v )

**Comment by robertjd** [comment] 2017-06-13 18:46
I am also having this problem.

**Comment by imagainstzy** [comment] 2017-07-16 14:49
I have the same problem，in code1.14.1 and preview1.1.5.

**Comment by copdips** [comment] 2017-08-10 11:36
same here code1.14.2 and preview1.1.5

**Comment by hsz1273327** [comment] 2017-08-20 12:23
the same

**Comment by searKing** [comment] 2017-09-10 17:07
This is caused by the process of loading the document changes.
It's fixed by v1.2.0, try it!

**Closed by searKing** 2017-09-10 17:07 UTC

**Comment by nils-ballmann** [comment] 2017-09-13 13:21
The error is still there in v1.2.0, but seemingly just because the compiled .js file in the extension doesn't contain the fix.

My workaround is to directly fix

    .vscode/extensions/searKing.preview-vscode-1.2.0/out/src/reStructuredTextDocumentContentManager.js

Change line 72 from

        if (!editor || editor.document) {

to 

        if (!editor || !editor.document) {

and then wait for the next version.

**Comment by nils-ballmann** [comment] 2017-09-13 13:28
Oh, sry, this is already fixed in 1.3.1. Nevermind. :) Had a code window with 1.2.0 still open.

**Comment by Mac-DevOSYandex** [comment] 2021-12-10 15:36
"No active editor. Abandoning command."
When I "Save All" but only have one active file...
Version: 1.63.0 (Universal)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:48.091Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
