### ISSUE TITLE
Issue with preview image

### ISSUE THREAD

**Issue by hellofedorov** [searKing/preview-vscode#10] opened 2017-03-15 11:10 UTC
Hello! Some image hostings have a feature to generate code for markdown code. Mononsnap can make it too. I have, for example, such code:
`![Alt text](https://monosnap.com/file/jEyRhdmYFQ2AoGCDy0webIJ1NeqInJ.png)`

But if I paste such code into VSC and open preview panel I have such image:
![Alt text](https://monosnap.com/file/wpf7VcLbTIWeC9UOnYMwLiJNE18D5D.png)

The image doesn't upload. I think it's because it's a not direct link on an image (if I open a link on the image I redirecting to another URL). 

But such code doesn;t work only your preview plugin. This code works in Github, works in other online services.

Can you fix it? 

Thanks!

**Comment by searKing** [comment] 2017-04-05 11:35
Thanks. After some tests, this is not caused by something like redirect URL.
It seems that we are hitting this electron bug: electron/electron#8366 which is caused by https://bugs.chromium.org/p/chromium/issues/detail?id=645629
VSCode Authors are working to pick up a new version of electron that will fix this.

**Comment by searKing** [comment] 2017-09-10 17:09
It's fixed by an upgrade of vscode,  a version vscode1.15.1 has been tested.

**Closed by searKing** 2017-09-10 17:09 UTC
