### ISSUE TITLE
Pug intelisense off the preview is on

### ISSUE THREAD

**Issue by ramonberrutti** [searKing/preview-vscode#19] opened 2017-09-30 00:59 UTC
Hi, perfect tool... I have a problem, when is installed the preview ext the syntax in .pug file are disable.
Like this:
![image](https://user-images.githubusercontent.com/7843855/31040725-398926e0-a561-11e7-84e8-d83898998131.png)

when need to be like this:
![image](https://user-images.githubusercontent.com/7843855/31040739-637d66f0-a561-11e7-859a-c267a9856cf4.png)

**Comment by joepagan** [comment] 2017-10-22 21:28
I can also confirm pug syntax highlighting is disabled when preview-vscode is enabled.

**Comment by yoyoys** [comment] 2017-11-02 02:47
Me too,
and pug icon is disappear

**Comment by Lorendin** [comment] 2017-11-16 19:11
Same issue when using Preview and reStructuredText extension together. Preview prevents the highlighting of the reStructuredText extension.

**Comment by David-Tsui** [comment] 2018-02-07 07:02
uninstalled

**Comment by JhonnyJason** [comment] 2018-02-28 10:51
same issue - when the extension is installed pug synthax highlighting vanishes - tsalinger from VS Code told me to open the issue here, but appears to be open already :-)

Cheers! And have fun fixing ;-)

**Comment by Tenrys** [comment] 2018-08-08 23:11
![](https://tenrys.pw/ShareX/2018/Aug/TGna.png)
![](https://tenrys.pw/ShareX/2018/Aug/fPi1.png)

For some reason the extension messes with Pug's language mode, or whatever.
There should be only one "jade" language labelled as Pug, instead there are two PUG and Pug languages with the same language name, the uppercase one is the bad one.

**Comment by searKing** [comment] 2018-10-29 12:50
It's fixed by V1.4.6.
This bug is caused by that, VSCode treats .pug' languages id as jade, while I treat .pug as pug...

**Closed by searKing** 2018-10-29 12:50 UTC
