### ISSUE TITLE
Doesn't open preview. "command '...Preview' not found"

### ISSUE THREAD

**Issue by IgorNovozhilov** [searKing/preview-vscode#7] opened 2017-02-13 08:18 UTC
![image](https://cloud.githubusercontent.com/assets/3082812/22875670/04a29bd2-f1de-11e6-9615-edbd34fb6f22.png)

win7 pro

Doesn't open preview

![image](https://cloud.githubusercontent.com/assets/3082812/22875545/644c24aa-f1dd-11e6-85e4-b9f79d78b112.png)
![image](https://cloud.githubusercontent.com/assets/3082812/22875520/400125fa-f1dd-11e6-8b05-b42bd1758803.png)
![image](https://cloud.githubusercontent.com/assets/3082812/22875527/46a578b6-f1dd-11e6-8fbf-4d99dbaccaf5.png)

**Comment by searKing** [comment] 2017-03-19 16:27
This BUG was caused by a vscode version compare bug, to  be  compatible with vscode's old APIs.
 It has been fixed now, and update **Preview** to 1.1.4 at least to have a try.

**Closed by searKing** 2017-03-19 16:27 UTC
